import { Link } from 'react-router-dom';
import { PageMeta } from '@/shared/components/PageMeta';
import { PageHeader } from '@/shared/layout/PageHeader';
import { PageShell } from '@/shared/layout/PageShell';
import { ROUTES } from '@/shared/constants/routes';

/**
 * /legal/disclaimer — full-page disclosure for Big Bull's simulated market nature.
 * This page is publicly accessible and indexable.
 */
export const Disclaimer = () => (
  <>
    <PageMeta
      title="Legal Disclaimer"
      description="Big Bull is an educational virtual investing platform. All market data is simulated and not real. This is not investment advice."
      path="/legal/disclaimer"
    />

    <PageShell>
      <div className="mx-auto max-w-3xl py-10">
        <PageHeader
          title="Legal Disclaimer"
          description="Please read this carefully before using Big Bull."
        />

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-foreground">
          {/* Section 1 */}
          <section>
            <h2 className="mb-2 text-base font-semibold">1. Educational Platform Only</h2>
            <p className="text-muted">
              Big Bull is an educational, paper-trading simulation platform designed to help users
              learn about financial markets and investing concepts. It is not a licensed broker,
              investment adviser, or financial intermediary of any kind.
            </p>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="mb-2 text-base font-semibold">
              2. Simulated Market Data — Not Real Prices
            </h2>
            <p className="text-muted">
              All prices, charts, NAV values, and portfolio returns shown on Big Bull are{' '}
              <strong className="font-semibold text-foreground">
                generated by the Market Simulation Engine (MSE)
              </strong>{' '}
              — a proprietary algorithm that produces realistic-looking price movements. They are{' '}
              <strong className="font-semibold text-foreground">
                not live, official, or real-time market data
              </strong>{' '}
              from any stock exchange, data vendor, or regulatory body. While Big Bull may reference
              real company names and ticker symbols for educational realism, the prices bear no
              relation to actual traded prices on NSE, BSE, or any other exchange.
            </p>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="mb-2 text-base font-semibold">3. Not Investment Advice</h2>
            <p className="text-muted">
              Nothing on Big Bull — including simulated portfolio values, returns, tax estimates, or
              AI Copilot responses — constitutes financial, investment, tax, or legal advice. Do not
              make real investment decisions based on anything displayed on this platform. Always
              consult a qualified financial adviser before investing real money.
            </p>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="mb-2 text-base font-semibold">4. No Affiliation with Exchanges</h2>
            <p className="text-muted">
              Big Bull is not affiliated with, endorsed by, or connected to the National Stock
              Exchange of India (NSE), the Bombay Stock Exchange (BSE), SEBI, AMFI, or any listed
              company whose name or ticker may appear on this platform. Company names and fund names
              are used solely for educational context.
            </p>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="mb-2 text-base font-semibold">5. Virtual Money Only</h2>
            <p className="text-muted">
              All trades on Big Bull use virtual currency. No real money is deposited, transferred,
              or invested through this platform. Simulated profits and losses have no real-world
              monetary value.
            </p>
          </section>

          {/* Section 6 */}
          <section>
            <h2 className="mb-2 text-base font-semibold">6. Verify Real Market Data Separately</h2>
            <p className="text-muted">
              For real market data, please refer to official and licensed sources such as{' '}
              <a
                href="https://www.nseindia.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary underline underline-offset-2"
              >
                NSE India
              </a>
              ,{' '}
              <a
                href="https://www.bseindia.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary underline underline-offset-2"
              >
                BSE India
              </a>
              , or your registered broker.
            </p>
          </section>

          {/* Back link */}
          <div className="border-t border-border pt-6">
            <Link to={ROUTES.EXPLORE} className="text-sm text-primary underline underline-offset-2">
              ← Back to Big Bull
            </Link>
          </div>
        </div>
      </div>
    </PageShell>
  </>
);

export default Disclaimer;
