import { Link } from 'react-router-dom';
import { ROUTES } from '@/shared/constants/routes';
import { cn } from '@/lib/utils';

/**
 * SimBanner — a compact, persistent disclaimer strip for all market-related pages.
 *
 * Communicates that prices are generated by the Market Simulation Engine (MSE)
 * and are not live or official market data.
 *
 * @param {string} [className] - Optional extra class names.
 */
export const SimBanner = ({ className }) => (
  <div
    role="note"
    aria-label="Simulated data notice"
    className={cn(
      'flex flex-wrap items-center justify-between gap-x-4 gap-y-1 rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-2.5 text-xs text-amber-900 dark:text-amber-100',
      className
    )}
  >
    <span>
      <strong className="font-semibold">Simulated data only.</strong> Prices, charts, and returns
      are generated by Big Bull&apos;s Market Simulation Engine — not live or official market data.
    </span>
    <Link
      to={ROUTES.DISCLAIMER}
      className="shrink-0 font-medium underline underline-offset-2 hover:opacity-80"
    >
      Learn more
    </Link>
  </div>
);

export default SimBanner;
