import { useParams, useLocation } from 'react-router-dom';
import { AppPageLayout } from '@/shared/layout/AppPageLayout';
import { PageMeta } from '@/shared/components/PageMeta';
import { SimBanner } from '@/shared/components/SimBanner';
import { MutualDetailContent } from '../components';
import { useGetAssetByTickerQuery } from '../api/marketApi';
import { buildMutualDetailPath } from '../constants/market';

/**
 * MutualDetail route — renders dynamic SEO meta tags based on the scheme code,
 * a persistent simulation disclaimer banner, and the full mutual fund detail content.
 */
export const MutualDetail = () => {
  const { schemeCode } = useParams();
  const location = useLocation();

  // Prefer the name passed via router state (from the list), then fall back to
  // the asset record fetched here, then the scheme code itself.
  const { data: asset } = useGetAssetByTickerQuery(schemeCode, { skip: !schemeCode });
  const displayName = location.state?.name || asset?.name || `Scheme ${schemeCode}`;

  const title = `${displayName} — Simulated Mutual Fund NAV`;
  const description = `View the simulated NAV, charts, and virtual trading for ${displayName} on Big Bull. This is paper-trading data generated by the Market Simulation Engine — not live NAV data.`;

  return (
    <>
      <PageMeta
        title={title}
        description={description}
        path={schemeCode ? buildMutualDetailPath(schemeCode) : undefined}
      />
      <AppPageLayout>
        <AppPageLayout.Content>
          <SimBanner className="mb-4" />
          <MutualDetailContent />
        </AppPageLayout.Content>
      </AppPageLayout>
    </>
  );
};

export default MutualDetail;
