import { useParams } from 'react-router-dom';
import { AppPageLayout } from '@/shared/layout/AppPageLayout';
import { PageMeta } from '@/shared/components/PageMeta';
import { SimBanner } from '@/shared/components/SimBanner';
import { StockDetailContent } from '../components';
import { useGetAssetByTickerQuery } from '../api/marketApi';
import { buildStockDetailPath } from '../constants/market';

/**
 * StockDetail route — renders dynamic SEO meta tags based on the ticker symbol,
 * a persistent simulation disclaimer banner, and the full stock detail content.
 */
export const StockDetail = () => {
  const { symbol } = useParams();

  // Fetch asset name for richer SEO — falls back to symbol if not yet loaded.
  const { data: asset } = useGetAssetByTickerQuery(symbol, { skip: !symbol });
  const displayName = asset?.name || symbol;

  const title = `${displayName} (${symbol}) — Simulated Stock Price`;
  const description = `View the simulated price, charts, and virtual trading for ${displayName} (${symbol}) on Big Bull. This is paper-trading data generated by the Market Simulation Engine — not live market data.`;

  return (
    <>
      <PageMeta
        title={title}
        description={description}
        path={symbol ? buildStockDetailPath(symbol) : undefined}
      />
      <AppPageLayout>
        <AppPageLayout.Content>
          <SimBanner className="mb-4" />
          <StockDetailContent />
        </AppPageLayout.Content>
      </AppPageLayout>
    </>
  );
};

export default StockDetail;
