/**
 * StockPriceHistory Model
 *
 * Stores every authoritative 30-second price point for STOCK assets,
 * as generated by the mseWorker BullMQ job.
 *
 * Design rules:
 *   - Written ONLY by the mseWorker — never by the 1s live ticker (mseLiveTicker).
 *   - Each document represents one 30-second tick for one stock.
 *   - Used exclusively for 1D chart data (intraday granularity).
 *   - Documents for the current calendar day are retained in full.
 *   - Previous days are superseded by DailyPrice records and can be pruned.
 *   - Mutual funds have no intraday history — use DailyPrice for MF NAV charts.
 *
 * Index strategy:
 *   - Compound index on (ticker, timestamp DESC) for fast time-range queries.
 *   - TTL index retains current-day + 1 extra day of intraday data (172 800s = 48 h).
 *     This keeps the collection lean while always covering today's full trading session
 *     regardless of timezone offsets.
 */
const mongoose = require('mongoose');

const stockPriceHistorySchema = new mongoose.Schema(
  {
    ticker: {
      type: String,
      required: [true, 'ticker is required'],
      uppercase: true,
      trim: true,
      index: true,
    },

    // Authoritative price written by the mseWorker BullMQ job.
    price: {
      type: Number,
      required: [true, 'price is required'],
      min: [0.01, 'price must be at least ₹0.01'],
    },

    // ₹ change vs. the immediately preceding 30-second tick for this asset.
    change: {
      type: Number,
      default: 0,
    },

    // Formatted percent string, e.g. "+1.23%" — mirrors the Redis payload shape.
    changePercent: {
      type: String,
      default: '+0.00%',
    },

    // When this tick was computed by the mseWorker.
    timestamp: {
      type: Date,
      required: [true, 'timestamp is required'],
    },
  },
  {
    // Collection-level timestamps disabled — we manage `timestamp` ourselves.
    timestamps: false,
    // Use a dedicated collection name so it's clear this is append-only history.
    collection: 'stockpricehistories',
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────────

// Primary query index: fetch all ticks for a ticker within a time window.
stockPriceHistorySchema.index({ ticker: 1, timestamp: -1 });

// TTL: auto-expire documents older than 48 hours.
// 48 h gives enough margin to always cover a full trading day even with
// timezone differences. Historical chart data beyond 1D is served from
// DailyPrice, so intraday documents beyond ~24 h are not needed.
stockPriceHistorySchema.index({ timestamp: 1 }, { expireAfterSeconds: 172800 }); // 48 h

module.exports = mongoose.model('StockPriceHistory', stockPriceHistorySchema);
